#31 product page featured product section
Scout-NU/powerhouse-site pull request #32
Opened 2021-04-01 00:46 UTC by camargov

I had issues viewing the text for the individual products on the product page, but I still styled the text so once the text is visible, less editing is needed and I was also wondering if the Featured Product section looks good enough.

2021-04-08 14:50 UTC, samgildea requested changes

2021-04-08 14:50 UTC, samgildea commented on src/components/products/products-styles.js
> +  font-size: calc(90px + (90 - 32) * ((100vw - 300px) / (1440 - 300)));
Now that we have a typography file we should just import H1 from the typography-styles.js

2021-04-08 14:50 UTC, samgildea commented on src/components/products/products-styles.js
> +  font-size: calc(20px + (20 - 16) * ((100vw - 300px) / (1440 - 300)));
Same here,  use predefined typography styles

2021-05-11 16:02 UTC, josephmannis requested changes
Little stuff, looks good otherwise!

2021-05-11 16:02 UTC, josephmannis commented on src/components/product_page/product-page.js
> +          {console.log(data.featured_product_image)}
Can you remove this please

2021-05-11 16:02 UTC, josephmannis commented on src/components/product_page/product-page.js
> +            {console.log(data)}
This too

2021-05-11 16:02 UTC, josephmannis commented on src/components/product_page/product-page.js
> +                <ProductCard href={`/${product.product.document.uid}`}>
Need a key

2021-05-11 16:02 UTC, josephmannis commented on src/components/product_page/product-page.js
> +          {console.log(data.products)}
Remove please

2021-05-11 16:02 UTC, josephmannis commented on src/components/product_page/product-page.js
> +                <ProductCard href={`/${product.product.document.uid}`}>
Need a key

2021-05-14 23:51 UTC, merged