#37 singular product page feature and spec section
Scout-NU/powerhouse-site pull request #47
Opened 2021-04-15 16:08 UTC by camargov

2021-04-15 17:48 UTC, samgildea requested changes

2021-04-15 17:48 UTC, samgildea commented on src/components/singular-product/singular-product.js
> +import React from "react"
This looks great so far!  Can you add this to the product template page in "/templates/product.js" and ultimately remove the singular product page javascript file as it is only necessary for generated product pages.

2021-04-15 17:48 UTC, samgildea commented on src/components/singular-product/singular-product-styles.js
> +  font-size: calc(40px + (40 - 32) * ((100vw - 300px) / (1440 - 300)));
Use the pre defined typography styles.

2021-04-15 17:48 UTC, samgildea commented on src/components/singular-product/singular-product-styles.js
> +  background-color: #C4C4C4;
Use colors from colors.js

2021-04-15 17:48 UTC, samgildea commented on src/components/singular-product/singular-product-styles.js
> +  background-color: #C4C4C4;
Use colors from colors.js

2021-04-15 17:48 UTC, samgildea commented on src/components/singular-product/singular-product-styles.js
> +  background-color: #C4C4C4;
Use colors from colors.js

2021-04-15 17:48 UTC, samgildea commented on src/components/singular-product/singular-product-styles.js
> +  font-size: calc(20px + (20 - 16) * ((100vw - 300px) / (1440 - 300)));
Use the pre defined typography styles.

2021-04-15 17:48 UTC, samgildea commented on src/components/singular-product/singular-product-styles.js
> +  font-size: calc(50px + (50 - 32) * ((100vw - 300px) / (1440 - 300)));
Use the pre defined typography styles.

2021-04-15 17:48 UTC, samgildea commented on src/components/singular-product/singular-product-styles.js
> +  font-size: calc(18px + (18 - 16) * ((100vw - 300px) / (1440 - 300)));
Use the pre defined typography styles.

2021-04-17 18:21 UTC, josephmannis requested changes
Few things!

2021-04-17 18:21 UTC, josephmannis commented on src/components/singular-product/singular-product.js
> +                      alt="Feature of a product"/>
Can this alt come from the CMS please

2021-04-17 18:21 UTC, josephmannis commented on src/components/singular-product/singular-product.js
> +                  <Feature>
The key should be in the top-level component

2021-04-17 18:21 UTC, josephmannis commented on src/templates/product.js
> +          <ProductType>{products.data.product_type}</ProductType>
Are these changes from the other PR? https://github.com/Scout-NU/powerhouse-site/pull/48#pullrequestreview-638265192 

If so, can you make sure you don't have stuff from other PRs in another in the future?

2021-04-17 18:21 UTC, josephmannis commented on src/templates/product.js
> +          {products.data.icons.map(icon => {
Keys!

2021-04-17 18:21 UTC, josephmannis commented on src/templates/product.js
> +          <img src={products.data.feature_icon.url} alt="Orange checklist icon" />
CMS alt please

2021-04-17 18:21 UTC, josephmannis commented on src/templates/product.js
> +              <Feature>
Keys at top level please

2021-04-17 18:21 UTC, josephmannis commented on src/templates/product.js
> +                    alt="Feature of a product"
CMS alt text please

2021-04-17 18:21 UTC, josephmannis commented on src/components/singular-product/singular-product.js
> +                    <IconImage></IconImage>
Are these supposed to contain something?

2021-05-11 15:58 UTC, josephmannis requested changes
Just a few little things

2021-05-11 15:58 UTC, josephmannis commented on src/components/about/about.js
> +          <img src={data.mission_image.url} />
Can you add the alt text from the CMS please?

2021-05-11 15:58 UTC, josephmannis commented on src/components/about/about.js
> +            <img src={data.mission_icon.url} />
Same here

2021-05-11 15:58 UTC, josephmannis commented on src/components/about/about.js
> +          <img src={data.industry_context_background_image.url} />
And here

2021-05-11 15:58 UTC, josephmannis commented on src/components/about/about.js
> +              <img src={data.industry_context_icon.url} />
Here too

2021-05-11 15:58 UTC, josephmannis commented on src/components/about/about.js
> +                      <img src={example.explanation_image.url} />
Here

2021-05-11 15:58 UTC, josephmannis commented on src/components/about/about.js
> +                  <img src={benefit.product_benefit_image.url} />
Alt

2021-05-11 15:58 UTC, josephmannis commented on src/components/about/about.js
> +                <>
Can you remove this fragment?

2021-05-11 15:58 UTC, josephmannis commented on src/components/about/about.js
> +                    <img src={member.team_member_image.url} />
Alt

2021-05-11 15:58 UTC, josephmannis commented on src/templates/product.js
> +            <img
Alt

2021-05-11 15:58 UTC, josephmannis commented on src/templates/product.js
> +                  {console.log(image)}
Can you remove this and the fragment please?

2021-05-11 15:58 UTC, josephmannis commented on src/templates/product.js
> +                <Feature>
Need a key

2021-05-15 19:30 UTC, merged