#8 contact page
Scout-NU/powerhouse-site pull request #55
Opened 2021-05-03 04:14 UTC by samgildea

2021-05-05 14:49 UTC, josephmannis commented
Also seeing a gql error here: 
```
error There was an error in your GraphQL query:

Cannot query field "how_description" on type "PrismicProcessPageData".

If you don't expect "how_description" to exist on the type "PrismicProcessPageData" it is most likely a typo.
However, if you expect "how_description" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "how_description" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "PrismicProcessPageData":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
```
I can review if you can resolve this real quick. Thanks!

2021-05-05 17:00 UTC, samgildea commented
Those graphql errors should be fixed for now.  A couple of the schemas have been updated for the process page and the solutions page which is causing them.

2021-05-07 16:26 UTC, josephmannis requested changes
Just two things!

2021-05-07 16:26 UTC, josephmannis commented on src/components/contact/contact.js
> +            <label>
Need form labels here:
https://www.w3.org/WAI/tutorials/forms/

Also the typography does not match the hi-fi designs.

2021-05-24 21:38 UTC, merged